config/routes.rb
Rails.application.routes.draw do
  resources :songs
  root "songs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chord.rb
class Chord < ApplicationRecord
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :chords
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :find_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = Song.all.order('title ASC')
  end

  def show
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)

    if @song.save
      redirect_to song_path(@song)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to song_path(@song)
    else
      render 'edit'
    end
  end

  def destroy
    @song.destroy
    redirect_to root_path
  end

  private

     def song_params
       params.require(:song).permit(
        :title, 
        :artist, 
        :difficulty,
        :lyrics,
        )
     end

     def find_song
      @song = Song.find_by(id: params[:id])
     end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cittearn2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= simple_form_for @song do |f| %>
  <%= f.input :title, label: "Song Title" %>
  <%= f.input :artist %>
  <%= f.input :difficulty, 
        :as => :select, 
        :collection => ['Beginner', 'Intermediate', 'Expert'], 
        :include_blank => false, 
        :label => "Difficulty" %>
  <%= f.input :lyrics %>
  <%= f.button :submit %>
<% end %>

app/views/songs/edit.html.erb
<%= render 'form' %>

app/views/songs/index.html.erb
<h1>Index View</h1>
<% @songs.each do |song| %>
  <h2><%= link_to song.title, song_path(song) %></h2>
<% end %>

<%= link_to "Add a Song", new_song_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>
<%= render 'form' %>

app/views/songs/show.html.erb
<div class="song-info">
  <h2 class="song-title"><%= @song.title %></h2>
  <h3 class="song-artist"><span>By</span> <%= @song.artist %></h3>
  <h3 class="song-difficulty"><%= @song.difficulty %></h3>
  <p class="song-lyrics"><%= @song.lyrics %></p>
</div>

<%= link_to "Edit Song", edit_song_path(@song) %>
<%= link_to "Delete Song", song_path(@song), method: :delete, data: { confirm: "Are you sure?" } %>